apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-observability
  namespace: observability
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: observability-vault-auth
  namespace: observability
spec:
  kubernetes:
    role: vso-observability
    serviceAccount: vso-observability
  vaultAuthGlobalRef:
    allowDefault: true
    namespace: platform