apiVersion: v1
kind: Secret
metadata:
  name: vault-ca
  namespace: ingress-traefik
  annotations:
    # Inject from the *Secret* that cert-manager already created for your CA
    cert-manager.io/inject-ca-from-secret: apps/vault-internal-ca
type: Opaque
