apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ../../base/kube-prometheus-stack
  - namespace.yaml
  - ingress-grafana.yaml
  - secrets
  - vso-config

configMapGenerator:
  - name: kube-prometheus-stack-values
    namespace: observability
    files:
      - values.yaml=values.yaml

generatorOptions:
  disableNameSuffixHash: true