apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
resources:
  - vso-pihole.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - configmap.yaml
  - pvc.yaml
  - secret-webpassword.yaml
  - service.yaml
  - serviceaccount.yaml
  - vso-pihole.yaml