apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform

resources:
  - ../../base/hashicorp-vault-secrets-operator
  - namespace.yaml
  - vault-auth-global.yaml

configMapGenerator:
  - name: vso-values
    namespace: platform
    files:
      - values.yaml=values.yaml

generatorOptions:
  disableNameSuffixHash: true