# See https://github.com/hashicorp/vault-secrets-operator/blob/main/chart/values.yaml


defaultVaultConnection:
  enabled: true
  address: "https://hashicorp-vault.platform.svc.cluster.local:8200"
  caCertSecret: "vault-internal-ca"
  tlsServerName: "hashicorp-vault.platform.svc.cluster.local"
  skipTLSVerify: false

  auth:
    kubernetes:
      role: "vso-operator"
      serviceAccount: "vault-secrets-operator-controller-manager"
      tokenAudiences: vault
