apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - helmrepository.yaml
  - secrets
  - vso-config
  - storageclass-defaults.yaml

configMapGenerator:
  - name: scaleway-csi-values
    namespace: platform
    files:
      - scaleway-csi-values.yaml

generatorOptions:
  disableNameSuffixHash: true
