apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ../../base/podinfo
  - namespace.yaml
transformers:
  - labels.yaml
patchesStrategicMerge:
  - patch-hpa.yaml
  - patch-color.yaml