apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        cfke.io/provider: scaleway
        topology.kubernetes.io/zone: nl-ams-1
      containers:
        - name: pihole
          env:
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  name: scw-pihole-webpassword
                  key: password
        
