apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - helmrepository.yaml


configMapGenerator:
  - name: hetzner-csi-values
    namespace: kube-system
    files:
      - hetzner-csi-values.yaml

generatorOptions:
  disableNameSuffixHash: true
