apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-ca-secret-sync
  namespace: ingress-traefik
spec:
  destination:
    create: true
    name: vault-ca
  hmacSecretData: true
  mount: kubernetes
  path: k8s/ingress-traefik
  type: kv-v2
  vaultAuthRef: traefik-vault-auth