apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: platform
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - vault
  defaultBackend:
    service:
      name: hashicorp-vault-ui-ts
      port:
        name: https
