---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform

resources:
  #- ../../base/hashicorp-vault
  #- namespace.yaml
  #- ingress.yaml

configMapGenerator:
  #- name: vault-values
  #  namespace: platform
  #  files:
  #    - values.yaml=values.yaml

generatorOptions:
  disableNameSuffixHash: true
