apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-secret-sync
  namespace: observability
spec:
  vaultAuthRef: platform/vault-auth # matches the auth mount path
  mount: kubernetes
  path: k8s/observability/grafana
  type: kv-v2
  refreshAfter: 5m
  destination:
    name: grafana
    create: true
    overwrite: true
