apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-secret-sync
  namespace: observability
spec:
  destination:
    create: true
    name: grafana
  hmacSecretData: true
  mount: secret
  path: k8s/observability
  type: kv-v2
  vaultAuthRef: observability-vault-auth