apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
resources:
  - ../../base/tailscale
  - namespace.yaml
  - secrets
  - vso-config

#configMapGenerator:
#- name: tailscale-values
#  namespace: tailscale
#  files:
#    - values.yaml=values.yaml

#generatorOptions:
#disableNameSuffixHash: true