apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
resources:
  - deployment.yaml
  - ingress.yaml
  - np-allow-bootstrap-to-pihole-http.yaml
  - np-allow-tailscale-to-pihole.yaml
  - configmap.yaml
  - pvc.yaml
  - service.yaml
  - serviceaccount.yaml
  - bootstrap-job.yaml