apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-traefik
resources:
  - ../../base/traefik
  - namespace.yaml
  - vault-ca-secret.yaml
  - serverstransport-vault.yaml

patchesStrategicMerge:
  - patch-helmrelease-values.yaml