apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-traefik
resources:
  #- ../../base/traefik
  #- namespace.yaml
  #- serverstransport-vault.yaml
  #- secrets
  #- vso-config

patchesStrategicMerge:
  #- patch-helmrelease-values.yaml