apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-kube-prometheus-stack-development
  namespace: flux-system
spec:
  interval: 60s
  path: ./gitops/apps/development/kube-prometheus-stack
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system