apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-traefik-development
  namespace: flux-system
spec:
  interval: 60s
  path: ./gitops/platform/development/traefik
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system